config/routes.rb
Spendon::Application.routes.draw do
  root :to => 'index#index'
  match 'sign_in' => 'index#index', :as => :sign_in, :via => [:get, :post]
  match 'sign_up' => 'index#sign_up', :as => :sign_up, :via => [:get, :post]
  match 'sign_out' => 'index#sign_out', :as => :sign_out
  match 'subjects' => 'home#index', :as => :subjects, :via => :get
  # match 'consumptions/new' => 'consumptions#new', :as => :new_consumption
  
  match 'subjects/categories' => 'subjects#categories', :as => :subject_categories, :via => [:get, :post]
  match 'categories/create' => 'categories#create', :as => :categories_create, :via => :post
  match 'categories/:cate_id' => 'categories#update', :as => :categories_update, :via => :post
  match 'categories/:cate_id' => 'categories#destroy', :as => :categories_delete, :via => :delete
  # match 'categories/get_categories' => 'categories#get_categories', :as => :get_categories, :via => :get

  resources :subjects do
    collection do
      get :filter_by_datetime
    end
  end

  resources :users do
    resources :blogs
  end

  match 'memo/update' => 'memos#update', :as => :update_memo, :via => :post

  scope 'settings', :controller => 'settings' do
    match 'basic', :as => :settings, :via => [:get, :post]
    match 'avatar', :as => :avatar_setting, :via => [:get, :post]
    match 'reset_password', :as => :reset_password, :via => [:get, :post]
  end

  match 'statistics' => 'statistics#index', :as => :statistics
  match 'statistics/chart' => 'statistics#chart', :as => :statistics_chart

  match 'home' => 'home#index', :as => :home

  namespace :admin do
    resources :users, :only => :index do
      collection do
        get :user_blogs
        get :user_subjects
        get :user_feed_backs
      end
    end
  end

  match 'feed_backs' => 'feed_backs#create', :as => :feed_backs, :via => :post

  match 'auth/weibo/callback' => 'auth#weibo_login'
  # match 'auth/developer/callback' => 'auth#login'
  
  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/statistics_controller.rb
# coding: utf-8
class StatisticsController < ApplicationController
  layout 'home'
  before_filter :require_login

  def index
    @user = current_user
    today = Time.now.at_beginning_of_day

    ['day', 'week', 'month', 'year'].each do |time|
      begun_at = self.instance_eval("Time.now.at_beginning_of_#{time}")
      self.instance_eval do 
        instance_variable_set("@#{time}_statistics", @user.subjects.where('created_at > ?', begun_at))
        instance_variable_set("@#{time}_total", eval("@#{time}_statistics.to_a.sum(&:total) || 0"))
        count = @user.consumptions.where('created_at > ?', begun_at).count
        instance_variable_set("@#{time}_count", count)
      end
    end

  end

  def chart
    @user = current_user
    uncated = @user.consumptions.where('category_id = 0 OR category_id is NULL').sum(&:cost).to_i
    @pie_chart_ary = @user.categories.collect do |category|
      name = category.name
      total = category.consumptions.to_a.sum(&:cost)
      [name, total.to_i]
    end
    @pie_chart_ary ||= []
    @pie_chart_ary = @pie_chart_ary.push(["未分类", uncated]).to_a

    last_time = Time.now.at_beginning_of_month
    first_time = last_time.ago(4.months)
    second_time = last_time.ago(3.months)
    third_time = last_time.ago(2.months)
    fifth_time = last_time.ago(1.months)

    @area_chart_ary = [first_time, second_time, third_time, fifth_time, last_time].collect do |end_time|
      time = "#{end_time.month}月"
      total = @user.subjects
        .where('created_at > ? and created_at < ?', end_time, end_time.since(1.month))
        .sum(&:total)
      [time, total.to_f]
    end.insert(0, ['月份', '消费总额'])
  end

end

app/views/statistics/_chart.haml
%script{ :type => 'text/javascript', :src => 'https://www.google.com/jsapi' }
:javascript    
  // Load the Visualization API and the piechart package.
  google.load('visualization', '1.0', {'packages':['corechart']});
  
  // Set a callback to run when the Google Visualization API is loaded.
  google.setOnLoadCallback(drawPieChart);

  // Callback that creates and populates a data table, 
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawPieChart() {

    // Get Data.
    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Topping');
    data.addColumn('number', 'Slices');
    data.addRows(#{@chart_ary});

    // Set chart options
    var options = {'title':'我的总消费结构图',
                   'width':400,
                   'height':300};

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.PieChart(document.getElementById('chart_area_div'));
    chart.draw(data, options);

  }
  google.load('visualization', '1.0', {'packages':['corechart']});
  google.setOnLoadCallback(drawAreaChart);

  function drawAreaChart() {
    var data = google.visualization.arrayToDataTable([
      ['Year', 'Sales', 'Expenses'],
      ['2004',  1000,      400],
      ['2005',  1170,      460],
      ['2006',  660,       1120],
      ['2007',  1030,      540]
    ]);

    var options = {
      title: 'Company Performance',
      hAxis: {title: 'Year',  titleTextStyle: {color: 'red'}}
    };

    var area_chart = new google.visualization.AreaChart(document.getElementById('chart_pie_div'));
    area_chart.draw(data, options);
  }

#chart_area_div{ :style => 'width:400px;height:300px;' }
#chart_pie_div{ :style => 'width:400px;height:300px;' }

app/views/statistics/chart.haml
- content_for :header_css do
  = stylesheet_link_tag 'statistics'

= nav_tab_tag([statistics_chart_path, '统计图'], [statistics_path, '概况'])
.content_detail
  %script{ :type => 'text/javascript', :src => 'https://www.google.com/jsapi' }
  :javascript    
    // Load the Visualization API and the piechart package.
    google.load('visualization', '1.0', {'packages':['corechart']});
    
    // Set a callback to run when the Google Visualization API is loaded.
    google.setOnLoadCallback(drawPieChart);

    // Callback that creates and populates a data table, 
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawPieChart() {

      // Get Data.
      // Create the data table.
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Topping');
      data.addColumn('number', 'Slices');
      data.addRows(#{@pie_chart_ary});

      // Set chart options
      var options = {'title':'我的消费构成',
                     'width':500,
                     'height':500};

      // Instantiate and draw our chart, passing in some options.
      var chart = new google.visualization.PieChart(document.getElementById('chart_pie_div'));
      chart.draw(data, options);

    }

    google.setOnLoadCallback(drawAreaChart);

    function drawAreaChart() {
      var data = google.visualization.arrayToDataTable(#{@area_chart_ary});

      var options = {
        title: '我的花钱趋势'
      };

      var area_chart = new google.visualization.AreaChart(document.getElementById('chart_area_div'));
      area_chart.draw(data, options);
    }

  #chart_area_div{ :style => 'width:600px;height:300px;' }
  #chart_pie_div{ :style => 'width:500px;height:500px;' }

app/views/statistics/index.haml
- content_for :header_css do
  = stylesheet_link_tag 'statistics'

= nav_tab_tag([statistics_chart_path, '统计图'], [statistics_path, '概况'])
.content_detail
  %dl.statistics_list.left
    %dt.orange
      今日统计
    %dd
      今日总消费: 
      %span= @day_total
      元
    %dd
      一共消费: 
      %span= @day_count
      笔
    %dd
      共有主题: 
      %span= @day_statistics.count
      个      
    %dd 
      平均每笔消费:
      %span= format '%.2f', @day_count.zero? ? 0 : (@day_total / @day_count)
      元

  %dl.statistics_list.left
    %dt.orange
      本周统计
    %dd
      本周总消费: 
      %span= @week_total
      元
    %dd
      一共消费: 
      %span= @week_count
      笔
    %dd
      共有主题: 
      %span= @week_statistics.count
      个      
    %dd 
      平均每笔消费:
      %span= format '%.2f', @week_count.zero? ? 0 : (@week_total / @week_count)
      元

  %dl.statistics_list.left
    %dt.orange
      本月统计
    %dd
      本月总消费: 
      %span= @month_total
      元
    %dd
      一共消费: 
      %span= @month_count
      笔
    %dd
      共有主题: 
      %span= @month_statistics.count
      个      
    %dd 
      平均每笔消费:
      %span= format '%.2f', @month_count.zero? ? 0 : (@month_total / @month_count)
      元

  %dl.statistics_list.left
    %dt.orange
      本年统计
    %dd
      本年总消费: 
      %span= @year_total
      元
    %dd
      一共消费: 
      %span= @year_count
      笔
    %dd
      共有主题: 
      %span= @year_statistics.count
      个      
    %dd 
      平均每笔消费:
      %span= format '%.2f', @year_count.zero? ? 0 : (@year_total / @year_count)
      元 