config/routes.rb
Spendon::Application.routes.draw do
  root :to => 'index#index'
  match 'sign_in' => 'index#index', :as => :sign_in, :via => [:get, :post]
  match 'sign_up' => 'index#sign_up', :as => :sign_up, :via => [:get, :post]
  match 'sign_out' => 'index#sign_out', :as => :sign_out
  match 'subjects' => 'home#index', :as => :subjects, :via => :get
  # match 'consumptions/new' => 'consumptions#new', :as => :new_consumption
  
  match 'subjects/categories' => 'subjects#categories', :as => :subject_categories, :via => [:get, :post]
  match 'categories/create' => 'categories#create', :as => :categories_create, :via => :post
  match 'categories/:cate_id' => 'categories#update', :as => :categories_update, :via => :post
  match 'categories/:cate_id' => 'categories#destroy', :as => :categories_delete, :via => :delete
  # match 'categories/get_categories' => 'categories#get_categories', :as => :get_categories, :via => :get

  resources :subjects do
    collection do
      get :filter_by_datetime
    end
  end

  resources :users do
    resources :blogs
  end

  match 'memo/update' => 'memos#update', :as => :update_memo, :via => :post

  scope 'settings', :controller => 'settings' do
    match 'basic', :as => :settings, :via => [:get, :post]
    match 'avatar', :as => :avatar_setting, :via => [:get, :post]
    match 'reset_password', :as => :reset_password, :via => [:get, :post]
  end

  match 'statistics' => 'statistics#index', :as => :statistics
  match 'statistics/chart' => 'statistics#chart', :as => :statistics_chart

  match 'home' => 'home#index', :as => :home

  namespace :admin do
    resources :users, :only => :index do
      collection do
        get :user_blogs
        get :user_subjects
        get :user_feed_backs
      end
    end
  end

  match 'feed_backs' => 'feed_backs#create', :as => :feed_backs, :via => :post

  match 'auth/weibo/callback' => 'auth#weibo_login'
  # match 'auth/developer/callback' => 'auth#login'
  
  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/home_controller.rb
# coding: utf-8
class HomeController < ApplicationController
  layout 'home'
  before_filter :require_login
  
  # def index
  #   @user = current_user
  #   @subjects = @user.subjects
  #   if params[:at_date].blank?
  #     case params[:date]
  #     when 'today'
  #       @subjects = @subjects.where('created_at > ?', Time.now.at_beginning_of_day)
  #     when 'weekly'
  #       @subjects = @subjects.where('created_at > ?', Time.now.at_beginning_of_week)
  #     when 'monthly'
  #       @subjects = @subjects.where('created_at > ?', Time.now.at_beginning_of_month)
  #     else
  #     end
  #   else
  #     @at_date = Date.parse(params[:at_date]).at_beginning_of_day
  #     @subjects = @subjects.where('created_at < ? and created_at > ?', @at_date.since(1.day), @at_date)
  #   end
  #   @subjects = @subjects.paginate(:page => params[:page], :per_page => 15).order('created_at DESC')
  # end


  def index
    @user = current_user
    @consumptions = @user.consumptions
    @json_ary = @consumptions.group_by { |c| c.created_at.at_beginning_of_day }.collect do |day, consumptions|
      total = consumptions.sum(&:cost)
      count_json = { :title => "共 #{consumptions.size} 笔", :start => day }.to_json
      cost_json = { :title => "￥#{total}", :start => day }.to_json
      [count_json, cost_json]
    end.flatten
  end
end

app/views/home/index.haml
- content_for :header_css do
  = stylesheet_link_tag 'cupertino/theme', 'fullcalendar'
  = stylesheet_link_tag 'fullcalendar.print', :media => 'print'

- content_for :header_js do
  = javascript_include_tag 'new_record', 'fullcalendar.min'

= nav_tab_tag([subjects_path, '消费记录'], [subject_categories_path, '设置消费类目'])

.content_detail
  #calendar

:javascript
  $(document).ready(function() {
    var events_ary = #{@json_ary};
    for (var i=0; i<events_ary.length; i++) {
      events_ary[i] = $.parseJSON(events_ary[i]);
    }

    $('#calendar').fullCalendar({
      theme: true,
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,basicWeek,basicDay'
      },

      eventRender: function(event, element) {
        element.bind('click', function() {
          var url = '/subjects/filter_by_datetime';
          $.get(url, { datetime : event.start }, function(data){
            if (data.success)
              Spendon.dialog($(data.html));
          }, 'json'); 
        });
        // alert shows up in linux chrome, but messes up draggable
      },      
      monthNames : ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
      monthNamesShort : ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
      dayNamesShort: ['日','一','二','三','四','五','六'],
      dayNames: ['周日','周一','周二','周三','周四','周五','周六'],
      editable: true,
      buttonText: {
        today: '今日',
        month: '按月',
        week: '按周',
        day: '按日'
      },
      events: events_ary
    });
  });