config/routes.rb
Spendon::Application.routes.draw do
  root :to => 'index#index'
  match 'sign_in' => 'index#index', :as => :sign_in, :via => [:get, :post]
  match 'sign_up' => 'index#sign_up', :as => :sign_up, :via => [:get, :post]
  match 'sign_out' => 'index#sign_out', :as => :sign_out
  match 'subjects' => 'home#index', :as => :subjects, :via => :get
  # match 'consumptions/new' => 'consumptions#new', :as => :new_consumption
  
  match 'subjects/categories' => 'subjects#categories', :as => :subject_categories, :via => [:get, :post]
  match 'categories/create' => 'categories#create', :as => :categories_create, :via => :post
  match 'categories/:cate_id' => 'categories#update', :as => :categories_update, :via => :post
  match 'categories/:cate_id' => 'categories#destroy', :as => :categories_delete, :via => :delete
  # match 'categories/get_categories' => 'categories#get_categories', :as => :get_categories, :via => :get

  resources :subjects do
    collection do
      get :filter_by_datetime
    end
  end

  resources :users do
    resources :blogs
  end

  match 'memo/update' => 'memos#update', :as => :update_memo, :via => :post

  scope 'settings', :controller => 'settings' do
    match 'basic', :as => :settings, :via => [:get, :post]
    match 'avatar', :as => :avatar_setting, :via => [:get, :post]
    match 'reset_password', :as => :reset_password, :via => [:get, :post]
  end

  match 'statistics' => 'statistics#index', :as => :statistics
  match 'statistics/chart' => 'statistics#chart', :as => :statistics_chart

  match 'home' => 'home#index', :as => :home

  namespace :admin do
    resources :users, :only => :index do
      collection do
        get :user_blogs
        get :user_subjects
        get :user_feed_backs
      end
    end
  end

  match 'feed_backs' => 'feed_backs#create', :as => :feed_backs, :via => :post

  match 'auth/weibo/callback' => 'auth#weibo_login'
  # match 'auth/developer/callback' => 'auth#login'
  
  match ':controller(/:action(/:id))(.:format)'
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/controllers/settings_controller.rb
# coding: utf-8
class SettingsController < ApplicationController
  layout 'home'
  before_filter :require_login, :init_user

  def basic
    # @user = current_user
    if request.post?
      @user.login = params[:login]
      if @user.save
        flash[:success] = '更新成功'
      else
        flash[:error] = @user.errors.full_messages.last
      end
      redirect_to :back
    end
  end

  def avatar
    # @user = current_user
    if request.post?
      @user.avatar = params[:avatar]
      flash[:error] = @user.errors.full_messages.last unless @user.save
      redirect_to :back
    end
  end

  def reset_password
    # @user = current_user
    if request.post?
      status = current_user.reset_password(params[:orig_password], params[:password], params[:password_confirmation])
      flash[status[0] ? :success : :error] = status[1]
      redirect_to :back
    end
  end

  protected
  def init_user
    @user = current_user
  end
end

app/views/settings/avatar.haml
- content_for :header_css do
  = stylesheet_link_tag 'setting'

= nav_tab_tag([settings_path, '基本设置'], [avatar_setting_path, '头像设置'], [reset_password_path, '修改密码'])
.content_detail
  = render 'shared/flash_notice'
  .avatar_setting_panel.clearfix
    = form_tag avatar_setting_path, :multipart => true do
      .current_avatar.left
        .box_title
          当前头像
        .container_box
          = image_tag @user.avatar_url(:large)
      .avatar_upload_form.left
        .box_title
          上传新头像
        .container_box
          = file_field_tag :avatar
          = hidden_field_tag :avatar_cache
          %p.mt10
            %input.button.submit{ :type => 'submit', :value => '上传' }

app/views/settings/basic.haml
- content_for :header_css do
  = stylesheet_link_tag 'setting'

= nav_tab_tag([settings_path, '基本设置'], [avatar_setting_path, '头像设置'], [reset_password_path, '修改密码'])
.content_detail
  .basic_setting_form
    = render 'shared/flash_notice'
    = form_tag settings_path do
      .email
        %span.title.left 邮箱：
        = @user.email
      .nickname
        %span.title.left 昵称：
        %input.form-text.w300{ :type => 'text', :value => @user.login, :name => 'login' }
      .actions
        %p.mt10
          %input.button.submit{ :type => 'submit', :value => '更新' }  

app/views/settings/reset_password.haml
- content_for :header_css do
  = stylesheet_link_tag 'setting'

= nav_tab_tag([settings_path, '基本设置'], [avatar_setting_path, '头像设置'], [reset_password_path, '修改密码'])
.content_detail
  = render 'shared/flash_notice'
  .reset_password_form
    = form_tag reset_password_path do 
      .orignal_password
        %span.title.left 旧密码：
        %input.form-text.w300{ :type => 'password', :name => 'orig_password' }
      .new_password
        %p
          %span.title.left 新密码：
          %input.form-text.w300{ :type => 'password', :name => 'password' }
        %p
          %span.title.left 确认新密码：
          %input.form-text.w300{ :type => 'password', :name => 'password_confirmation' }
      .actions
        %p.mt10
          %input.button.submit{ :type => 'submit', :value => '确认' }        