config/routes.rb
Spendon::Application.routes.draw do
  root :to => 'index#index'
  match 'sign_in' => 'index#index', :as => :sign_in, :via => [:get, :post]
  match 'sign_up' => 'index#sign_up', :as => :sign_up, :via => [:get, :post]
  match 'sign_out' => 'index#sign_out', :as => :sign_out
  match 'subjects' => 'home#index', :as => :subjects, :via => :get
  # match 'consumptions/new' => 'consumptions#new', :as => :new_consumption
  
  match 'subjects/categories' => 'subjects#categories', :as => :subject_categories, :via => [:get, :post]
  match 'categories/create' => 'categories#create', :as => :categories_create, :via => :post
  match 'categories/:cate_id' => 'categories#update', :as => :categories_update, :via => :post
  match 'categories/:cate_id' => 'categories#destroy', :as => :categories_delete, :via => :delete
  # match 'categories/get_categories' => 'categories#get_categories', :as => :get_categories, :via => :get

  resources :subjects do
    collection do
      get :filter_by_datetime
    end
  end

  resources :users do
    resources :blogs
  end

  match 'memo/update' => 'memos#update', :as => :update_memo, :via => :post

  scope 'settings', :controller => 'settings' do
    match 'basic', :as => :settings, :via => [:get, :post]
    match 'avatar', :as => :avatar_setting, :via => [:get, :post]
    match 'reset_password', :as => :reset_password, :via => [:get, :post]
  end

  match 'statistics' => 'statistics#index', :as => :statistics
  match 'statistics/chart' => 'statistics#chart', :as => :statistics_chart

  match 'home' => 'home#index', :as => :home

  namespace :admin do
    resources :users, :only => :index do
      collection do
        get :user_blogs
        get :user_subjects
        get :user_feed_backs
      end
    end
  end

  match 'feed_backs' => 'feed_backs#create', :as => :feed_backs, :via => :post

  match 'auth/weibo/callback' => 'auth#weibo_login'
  # match 'auth/developer/callback' => 'auth#login'
  
  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/admin.haml
<!DOCTYPE html>
%html
  %head
    %title 花哪儿了 - 后台管理
    = stylesheet_link_tag 'application', 'admin'
    %link{ :href => image_path('favicon.ico'), :rel => 'shortcut icon', :type => 'image/vnd.microsoft.icon' }
    = csrf_meta_tags
  %body
    .manage_panel
      .navigation
        %ul
          %li
            %a{ :href => admin_users_path } 新注册用户
          %li
            %a{ :href => admin_users_path(:order_by => 'login_time') } 最近有登录的用户
          %li
            %a{ :href => user_blogs_admin_users_path } 日志列表
          %li
            %a{ :href => user_subjects_admin_users_path } 主题列表
          %li
            %a{ :href => user_feed_backs_admin_users_path } 反馈建议            

      .list_container                                    
        = yield

app/views/layouts/application.haml
<!DOCTYPE html>
%html
  %head
    %title 花哪儿了 - 简单记录每日消费的工具
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    %link{ :href => image_path('favicon.ico'), :rel => 'shortcut icon', :type => 'image/vnd.microsoft.icon' }
    = csrf_meta_tags
  %body
    = yield
    .footer.clearfix
      = mail_to 'jimmy.huangjin@gmail.com', 'jimmy.huangjin@gmail.com'
      © 2012 花哪儿了
      
= render 'shared/google_analytics'

app/views/layouts/home.haml
<!DOCTYPE html>
%html
  %head
    %title 花哪儿了 - 简单记录每日消费的工具
    = stylesheet_link_tag 'home', 'application', 'global', 'jquery-ui.custom'
    = yield :header_css
    = javascript_include_tag 'application', 'jquery-ui-1.8.17.custom.min', 'memo', 'consumption', 'feed_back'
    = yield :header_js
    %link{ :href => image_path('favicon.ico'), :rel => 'shortcut icon', :type => 'image/vnd.microsoft.icon' }
    %meta{ :name => 'keywords', :content => '花哪儿了，随手记，简单记录消费工具，Ruby, Rails' }
    %meta{ :name => 'description', :content => '一个简洁的在线记录每日消费的工具' }
    = csrf_meta_tags
    :javascript
      Spendon.user_categories = #{current_user.categories.select([:id, :name]).collect{ |cate| [cate.id, cate.name] }}
  %body
    .home-main-container
      .header-container
        .site-name.left
          = link_to '花哪儿了', home_path
        / %ul.navigation
        /   %li
        /     %a{ :href => '#' } 讨论组
        .settings.right
          %ul
            %li
              = link_to @user.login, 'javascript:;', :class => 'dropdown-toggle'
              %ul.dropdown
                %li
                  = link_to '账号设置', settings_path
                %li
                  = link_to '退出登录', sign_out_path
      .main-container
        .left-container
          .user_info
            %dl
              %dt.avatar
                %a{ :href => avatar_setting_path }
                  = image_tag(@user.avatar_url(:normal), :size => '50x50')
              %dd.user_name
                = @user.login || 'Huang Jin'
              %dd.record_days
                %p
                  已有记录
                  %span= @user.consumptions_count
                  笔
                %p
                  连续记录 
                  %span= @user.recorded_days 
                  天
          .menu.clearfix
            %ul
              %li{ :class => params[:controller] == 'subjects' || params[:controller] == 'home' ? 'checked' : nil }
                %a{ :href => subjects_path } 
                  = image_tag 'spend.gif'
                  消费
              %li{ :class => params[:controller] == 'statistics' ? 'checked' : nil }
                %a{ :href => statistics_chart_path }
                  = image_tag 'statistics16.png'
                  统计
              / %li
              /   %a{ :href => 'javascript:;' } 
              /     = image_tag 'remander.gif'
              /     提醒
              %li{ :class => params[:controller] == 'blogs' ? 'checked' : nil }
                %a{ :href => user_blogs_path(current_user) }
                  = image_tag 'blog.gif'
                  日记
              %li{ :class => params[:controller] == 'settings' ? 'checked' : nil }
                %a{ :href => settings_path }
                  = image_tag 'setting16.png'
                  设置                                                                  
        .mid-container
          = yield
        .right-container
          .new_consumptions{ :align => 'center' }
            %input.button.new_record_submit.newConsumption{ :type => 'submit', :value => '新建消费记录' }
          .memo
            .text
              %p{ :title => '点击可以编辑' }= @user.memos.last.try(:content) || '这里是便笺，你可以随意写点什么，点击开始编辑'
              %textarea
    .footer.clearfix
      %p
        推荐使用 Chrome 或 Firefox 浏览器获取最佳浏览体验
      %p
        = mail_to 'jimmy.huangjin@gmail.com', 'jimmy.huangjin@gmail.com'
        © 2012 花哪儿了
      .friend_sites
        友情链接：
        %a{ :href => 'http://720p.so', :target => '_blank' } 720p.so
        &nbsp;&nbsp;
        %a{ :href => 'http://www.aodi.com', :target => '_blank' } 奥迪车友会

    .feedback_btn.feedBack
      反馈建议
      
= render 'shared/google_analytics'                    

app/views/layouts/public.haml
<!DOCTYPE html>
%html
  %head
    %title 花哪儿了 - 简单记录每日消费的工具
    = stylesheet_link_tag 'public', 'global'
    = yield :header_css
    = javascript_include_tag 'application'
    = yield :header_js
    %link{ :href => image_path('favicon.ico'), :rel => 'shortcut icon', :type => 'image/vnd.microsoft.icon' }
    = csrf_meta_tags
    %meta{ :name => 'keywords', :content => '花哪儿了，随手记，简单记录消费工具，Ruby, Rails' }
    %meta{ :name => 'description', :content => '一个简洁的在线记录每日消费的工具' }

  %body
    .public-main-container
      = yield
    .footer.clearfix
      %p
        推荐使用 Chrome 或 Firefox 浏览器获取最佳浏览体验
      %p
        = mail_to 'jimmy.huangjin@gmail.com', 'jimmy.huangjin@gmail.com'
        © 2012 花哪儿了
      .friend_sites
        友情链接：
        %a{ :href => 'http://720p.so', :target => '_blank' } 720p.so        
        &nbsp;&nbsp;
        %a{ :href => 'http://www.aodi.com', :target => '_blank' } 奥迪车友会      
= render 'shared/google_analytics'
= render 'shared/baidu_share'